[features]
seeds = false
skip-lint = false

[programs.localnet]
universal_nft = "UNv1NFTRK111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node ./tests/universal_nft.js"
