[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.devnet]
universal_nft = "7bwYem3NvksZcsmgBLtNbQLkS1p35ahHa7JsssKeQ8UT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-node --transpile-only ./tests/universal_nft.ts"
