[features]
seeds = false
skip-lint = false

[programs.localnet]
universal_nft = "B5o6iRGvxvC8hL5tUTjV8dmu4GwFpnfH5ZssAedNt2Yp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-node --transpile-only ./tests/universal_nft.ts"
