[workspace]
resolver = "2"

members = [
    "programs/universal_nft"
]

[profile.release]
opt-level = "s"
overflow-checks = true

[patch.crates-io]
# Pin to a solana-program version compatible with rustc 1.75 used by Solana 1.18.26 toolchain
solana-program = "=2.2.2"
