[workspace]
resolver = "2"

members = [
    "programs/universal_nft"
]

[profile.release]
opt-level = "s"
overflow-checks = true

[patch.crates-io]
# Pin to Solana program crate compatible with rustc in Solana 1.18.x toolchain
solana-program = "=2.2.2"
