name: Build & Test (Anchor + Node)

on:
  pull_request:
  push:
    branches: [ feat/universal-nft-solana ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Rust
      - name: Setup Rust (1.69.0 for lockfile v3)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.69.0"
          components: rustfmt, clippy

      # Install system dependencies
      - name: Install system dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libudev-dev libusb-1.0-0-dev curl nodejs npm git build-essential

      # Install Solana CLI
      - name: Install Solana CLI
        run: |
          set -euo pipefail
          ver=v1.18.26
          curl -sSfL https://github.com/solana-labs/solana/releases/download/${ver}/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
          tar -xjf solana.tar.bz2
          export PATH="$PWD/solana-release/bin:$PATH"
          echo "$PWD/solana-release/bin" >> "$GITHUB_PATH"
          solana --version

      # Init local validator and wallet
      - name: Init local validator and wallet
        run: |
          set -euo pipefail
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase -f -s
          solana config set --url http://127.0.0.1:8899
          nohup solana-test-validator --reset --quiet >/dev/null 2>&1 &
          sleep 15
          solana cluster-version

      # Build Anchor CLI locally (v0.31.1)
      - name: Build Anchor CLI locally
        run: |
          set -euxo pipefail
          git clone --branch v0.31.1 https://github.com/coral-xyz/anchor.git
          cd anchor
          cargo build --release -p anchor-cli
          export PATH="$PWD/target/release:$PATH"
          anchor --version

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Node dependencies
      - name: Install Node deps
        working-directory: protocol-contracts-solana
        run: |
          npm ci || npm i
          jq -r .dependencies < package.json || true

      # Anchor build (no validator)
      - name: Anchor build
        working-directory: protocol-contracts-solana
        run: |
          git rm -f --cached Cargo.lock || true
          rm -f Cargo.lock || true
          anchor clean || true
          rustup override set 1.69.0
          cargo generate-lockfile
          RUSTUP_TOOLCHAIN=1.69.0 anchor build

      # Run TypeScript tests
      - name: Run TS tests
        working-directory: protocol-contracts-solana
        run: |
          npm test --silent
