name: Cross-chain NFT CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Solana CLI
      - name: Set up Solana
        run: |
          # Download Solana CLI from GitHub releases (more reliable than release.solana.com)
          SOLANA_VERSION="1.17.0"
          wget -qO- "https://github.com/solana-labs/solana/releases/download/v${SOLANA_VERSION}/solana-release-x86_64-unknown-linux-gnu.tar.bz2" | tar -xjf -
          echo "$PWD/solana-release/bin" >> $GITHUB_PATH
          export PATH="$PWD/solana-release/bin:$PATH"
          solana --version

      # 3. Set up Rust (needed for Solana + Anchor programs)
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Verify Rust
        run: rustc --version

      # 4. Install Anchor
      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install latest
          avm use latest
          anchor --version

      # 5. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 6. Install Node deps
      - name: Install dependencies
        run: |
          cd contracts/nft
          npm install

      # 7. Deploy to Base Sepolia (EVM)
      - name: Deploy Universal NFT to Base Sepolia
        run: |
          cd contracts/nft
          npx hardhat run scripts/deploy-base-sepolia.js --network base-sepolia
        env:
          PRIVATE_KEY: ${{ secrets.EVM_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC }}

      # 8. Deploy to ZetaChain testnet
      - name: Deploy Universal NFT to ZetaChain
        run: |
          cd contracts/nft
          npx hardhat run scripts/deploy-zetachain.js --network zeta-testnet
        env:
          PRIVATE_KEY: ${{ secrets.EVM_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.ZETACHAIN_RPC }}

      # 9. Deploy to Solana Devnet
      - name: Deploy Solana NFT program
        run: |
          echo '${{ secrets.SOLANA_KEYPAIR }}' > ~/.config/solana/id.json
          cd protocol-contracts-solana
          anchor build
          anchor deploy --provider.cluster devnet
        env:
          SOLANA_RPC_URL: ${{ secrets.SOLANA_DEVNET_RPC }}

      # 10. Capture Solana deployment details
      - name: Capture Solana deployment info
        run: |
          cd contracts/nft
          node scripts/deploy-solana.js

      # 11. Run cross-chain NFT transfer tests
      - name: Run cross-chain transfer tests
        run: |
          cd contracts/nft
          node scripts/crosschain-test.js
        env:
          PRIVATE_KEY: ${{ secrets.EVM_PRIVATE_KEY }}
          BASE_RPC: ${{ secrets.BASE_SEPOLIA_RPC }}
          ZETA_RPC: ${{ secrets.ZETACHAIN_RPC }}
          SOLANA_KEYPAIR: ${{ secrets.SOLANA_KEYPAIR }}
          SOLANA_RPC: ${{ secrets.SOLANA_DEVNET_RPC }}

      # 12. Upload result file
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: crosschain-results
          path: contracts/nft/results.json

      # 13. Comment results on PR
      - name: Comment results
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: contracts/nft/results.md
