name: Solana Devnet Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feat/universal-nft-solana

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ANCHOR_PROVIDER_URL: https://api.devnet.solana.com
      ANCHOR_WALLET: ${{ github.workspace }}/id.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Solana wallet from secret
        shell: bash
        run: |
          echo '${{ secrets.SOLANA_WALLET_KEY }}' > $ANCHOR_WALLET
          chmod 600 $ANCHOR_WALLET

      - name: Install Rust 1.79
        shell: bash
        run: |
          rustup install 1.79.0
          rustup override set 1.79.0
          rustc --version
          cargo --version

      - name: Install Solana 1.18.33 (bundles Rust >=1.79 for SBF)
        shell: bash
        run: |
          sudo apt-get update -y && sudo apt-get install -y curl
          set -euo pipefail
          curl -sSfL https://github.com/solana-labs/solana/releases/download/v1.18.33/solana-install-init-x86_64-unknown-linux-gnu \
            -o /tmp/solana-install-init
          chmod +x /tmp/solana-install-init
          /tmp/solana-install-init v1.18.33
          echo "$HOME/.local/share/solana/install/active_release/solana-release/bin" >> $GITHUB_PATH
          solana --version || true
          cargo-build-sbf --version || true

      - name: Create wallet if secret not provided
        shell: bash
        run: |
          if [ ! -s "$ANCHOR_WALLET" ]; then
            echo "No SOLANA_WALLET_KEY secret provided; generating ephemeral devnet keypair"
            solana-keygen new --no-bip39-passphrase --outfile "$ANCHOR_WALLET" --force
            chmod 600 "$ANCHOR_WALLET"
          fi
          solana config set --url https://api.devnet.solana.com >/dev/null 2>&1 || true
          solana address -k "$ANCHOR_WALLET"

      - name: Install Anchor CLI
        shell: bash
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
          anchor --version

      - name: Clean previous builds
        working-directory: protocol-contracts-solana
        shell: bash
        run: anchor clean

      - name: Build Solana program (Rust 1.79)
        working-directory: protocol-contracts-solana
        shell: bash
        run: |
          cargo-build-sbf --version
          cargo +1.79.0 --version
          cargo-build-sbf --manifest-path programs/universal_nft/Cargo.toml --sbf-out-dir target/deploy

      - name: List deploy artifacts
        working-directory: protocol-contracts-solana
        shell: bash
        run: ls -l target/deploy || true

      - name: Deploy to Devnet
        working-directory: protocol-contracts-solana
        shell: bash
        run: anchor deploy --provider.cluster devnet

      - name: Print deployed program address
        working-directory: protocol-contracts-solana
        shell: bash
        run: solana address -k target/deploy/universal_nft-keypair.json

      - name: Upload program artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal_nft_artifacts
          path: |
            protocol-contracts-solana/target/deploy/universal_nft.so
            protocol-contracts-solana/target/deploy/universal_nft-keypair.json
          if-no-files-found: warn


