name: Test (Anchor + Node)

on:
  pull_request:
  push:
    branches: [ feat/universal-nft-solana ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust (1.69.0 for lockfile v3)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.69.0"
          components: rustfmt, clippy

      - name: Install system dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libudev-dev libusb-1.0-0-dev curl nodejs npm

      - name: Install Solana CLI (GitHub fallback)
        run: |
          set -euo pipefail
          ver=v1.18.26
          curl -sSfL https://github.com/solana-labs/solana/releases/download/${ver}/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
          tar -xjf solana.tar.bz2
          export PATH="$PWD/solana-release/bin:$PATH"
          echo "$PWD/solana-release/bin" >> "$GITHUB_PATH"
          solana --version

      - name: Init local validator and wallet
        run: |
          set -euo pipefail
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase -f -s
          solana config set --url http://127.0.0.1:8899
          nohup solana-test-validator --reset --quiet >/dev/null 2>&1 &
          sleep 15
          solana cluster-version

      - name: Install Anchor via AVM (0.31.1 pre-built binary)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euxo pipefail
          mkdir -p ~/.avm/bin
          curl -sSfL https://github.com/coral-xyz/anchor/releases/download/v0.31.1/avm-linux-x86_64.tar.gz | tar -xz -C ~/.avm/bin
          export PATH="$HOME/.avm/bin:$PATH"
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          avm use 0.31.1
          anchor --version

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        working-directory: protocol-contracts-solana
        run: |
          npm ci || npm i
          jq -r .dependencies < package.json || true

      - name: Anchor build (no validator)
        working-directory: protocol-contracts-solana
        run: |
          git rm -f --cached Cargo.lock || true
          rm -f Cargo.lock || true
          anchor clean || true
          rustup override set 1.69.0
          cargo generate-lockfile
          RUSTUP_TOOLCHAIN=1.69.0 anchor build

      - name: Run TS tests
        working-directory: protocol-contracts-solana
        run: |
          npm test --silent
